src/src/Models/ErrorViewModel.cs
namespace CourseWork.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

src/src/Controllers/HomeController.cs
using System.Diagnostics;
using CourseWork.Models;
using Microsoft.AspNetCore.Mvc;

namespace CourseWork.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }
    
   
    public IActionResult Index() => View();

    
    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
    }
}

src/src/Controllers/MapController.cs
using Microsoft.AspNetCore.Mvc;
using CourseWork.MapGen;
namespace CourseWork.Controllers;

public class MapController:Controller
{
    private static Map _map = null!;
    [HttpGet]
    public IActionResult Index() => View();
    
    [HttpPost]
    public IActionResult Index(int? sizeId, int? lenOfPix, bool? hasRiver=false, bool? hasCastles=false, bool? hasParticles=false)
    {
        int[] numbers = {200, 300, 400, 500, 600, 700, 800};
        var side = numbers[sizeId.GetValueOrDefault(0)];
        var mapBuilder = new MapBuilder(side, side, lenOfPix.GetValueOrDefault(1));
        _map = mapBuilder.BuildMap(hasRiver.GetValueOrDefault(false),hasCastles.GetValueOrDefault(false),hasParticles.GetValueOrDefault(false));
        ViewBag.Map = _map;
        return View("DrawHeightMap");
    }

    
    public IActionResult DrawHeightMap()
    {
        ViewBag.Map = _map;
        return View();
    }
    
    public IActionResult DrawHeatMap()
    { 
        ViewBag.Map = _map;
       return View();
    }
    
    public IActionResult DrawMoistureMap()
    {
        ViewBag.Map = _map;
        return View();
    }
    public IActionResult DrawBiomeMap()
    {
        ViewBag.Map = _map;
        return View();
    }
}

src/src/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/src/Views/Map/DrawBiomeMap.cshtml
@{
    Layout = "_Layout2";
    ViewData["Title"] = "Biome Map";
}

@{
    int newWidth = ViewBag.Map.Width*ViewBag.Map.LenOfPixel+10*ViewBag.Map.LenOfPixel;
    int newHeight = ViewBag.Map.Height*ViewBag.Map.LenOfPixel+10*ViewBag.Map.LenOfPixel;
}

<script>
    window.onload = () => {
        const canvasId = ["canvas1","canvas2","canvas3","canvas4"].map((id) => {
            const element = document.getElementById(id);
            if (element) {
                return element.getContext('2d');
            }
        });
        let startX = 10;
        let startY = 10;
        @for (int x = 0; x < ViewBag.Map.Width; x++)
        {
            @for (int y = 0; y < ViewBag.Map.Height; y++)
            {
                <text>
                    drawRect(canvasId, startX,startY,@ViewBag.Map.Tiles[x, y].BiomeInfo.Color.Red,
                                                                    @ViewBag.Map.Tiles[x, y].BiomeInfo.Color.Green,
                                                                    @ViewBag.Map.Tiles[x, y].BiomeInfo.Color.Blue,
                                                                    @ViewBag.Map.LenOfPixel,3);
                    startX += @ViewBag.Map.LenOfPixel;
                </text>
            }
            <text>
                startX = 10;
                startY += @ViewBag.Map.LenOfPixel;
            </text>
        }
    };
</script>
<body>
<canvas id="canvas4" width="@newWidth" height="@newHeight"></canvas>
    @Html.ActionLink("Prev", "DrawMoistureMap", "Map")
    @Html.ActionLink("Restart", "Index", "Map")
    @Html.ActionLink("Next", "DrawHeightMap", "Map")
<button onclick="saveCanvasAsImageFile(3,`Biome Map`)">
Download
</button>
</body>

src/src/Views/Map/DrawHeatMap.cshtml
@{
    Layout = "_Layout2";
    ViewData["Title"] = "Heat Map";
}

@{
    int newWidth = ViewBag.Map.Width*ViewBag.Map.LenOfPixel+10*ViewBag.Map.LenOfPixel;
    int newHeight = ViewBag.Map.Height*ViewBag.Map.LenOfPixel+10*ViewBag.Map.LenOfPixel;
}

<script>
    window.onload = () => {
        const canvasId = ["canvas1","canvas2","canvas3","canvas4"].map((id) => {
            const element = document.getElementById(id);
            if (element) {
                return element.getContext('2d');
            }
        });
        let startX = 10;
        let startY = 10;
        @for (int x = 0; x < ViewBag.Map.Width; x++)
        {
            @for (int y = 0; y < ViewBag.Map.Height; y++)
            {
                <text>
                    drawRect(canvasId, startX,startY,@ViewBag.Map.Tiles[x, y].HeatInfo.Color.Red,
                                                                    @ViewBag.Map.Tiles[x, y].HeatInfo.Color.Green,
                                                                    @ViewBag.Map.Tiles[x, y].HeatInfo.Color.Blue,
                                                                    @ViewBag.Map.LenOfPixel,1);
                    startX += @ViewBag.Map.LenOfPixel;
                </text>
            }
            <text>
                startX = 10;
                startY += @ViewBag.Map.LenOfPixel;
            </text>
        }
    };
</script>
<body>
<canvas id="canvas2" width="@newWidth" height="@newHeight"></canvas>
   @Html.ActionLink("Prev", "DrawHeightMap", "Map")
   @Html.ActionLink("Restart", "Index", "Map")
   @Html.ActionLink("Next", "DrawMoistureMap", "Map")
  <button onclick="saveCanvasAsImageFile(1,`Heat Map`)">
  Download
  </button>
</body>

src/src/Views/Map/DrawHeightMap.cshtml
@{
    Layout = "_Layout2";
    ViewData["Title"] = "Height Map";
}

@{
    int newWidth = ViewBag.Map.Width*ViewBag.Map.LenOfPixel+10*ViewBag.Map.LenOfPixel;
    int newHeight = ViewBag.Map.Height*ViewBag.Map.LenOfPixel+10*ViewBag.Map.LenOfPixel;
}

<script>
    window.onload = () => {
        const canvasId = ["canvas1","canvas2","canvas3","canvas4"].map((id) => {
            const element = document.getElementById(id);
            if (element) {
                return element.getContext('2d');
            }
        });
        let startX = 10;
        let startY = 10;
        @for (int x = 0; x < ViewBag.Map.Width; x++)
        {
            @for (int y = 0; y < ViewBag.Map.Height; y++)
            {
                <text>
                    drawRect(canvasId, startX,startY,@ViewBag.Map.Tiles[x, y].HeightInfo.Color.Red,
                                                                    @ViewBag.Map.Tiles[x, y].HeightInfo.Color.Green,
                                                                    @ViewBag.Map.Tiles[x, y].HeightInfo.Color.Blue,
                                                                    @ViewBag.Map.LenOfPixel,0);
                    startX += @ViewBag.Map.LenOfPixel;
                </text>
            }
            <text>
                startX = 10;
                startY += @ViewBag.Map.LenOfPixel;
            </text>
        }
    };
</script>
<body>
<canvas id="canvas1" width="@newWidth" height="@newHeight"></canvas>
    @Html.ActionLink("Prev", "DrawBiomeMap", "Map")
    @Html.ActionLink("Restart", "Index", "Map")
    @Html.ActionLink("Next", "DrawHeatMap", "Map")
<button onclick="saveCanvasAsImageFile(0,`Height Map`)">
Download
</button>
</body>

src/src/Views/Map/DrawMoistureMap.cshtml
@{
    Layout = "_Layout2";
    ViewData["Title"] = "Moisture Map";
}
@{
    int newWidth = ViewBag.Map.Width*ViewBag.Map.LenOfPixel+10*ViewBag.Map.LenOfPixel;
    int newHeight = ViewBag.Map.Height*ViewBag.Map.LenOfPixel+10*ViewBag.Map.LenOfPixel;
}

<script>
    window.onload = () => {
        const canvasId = ["canvas1","canvas2","canvas3","canvas4"].map((id) => {
            const element = document.getElementById(id);
            if (element) {
                return element.getContext('2d');
            }
        });
        let startX = 10;
        let startY = 10;
        @for (int x = 0; x < ViewBag.Map.Width; x++)
        {
            @for (int y = 0; y < ViewBag.Map.Height; y++)
            {
                <text>
                    drawRect(canvasId, startX,startY,@ViewBag.Map.Tiles[x, y].MoistureInfo.Color.Red,
                                                                    @ViewBag.Map.Tiles[x, y].MoistureInfo.Color.Green,
                                                                    @ViewBag.Map.Tiles[x, y].MoistureInfo.Color.Blue,
                                                                    @ViewBag.Map.LenOfPixel,2);
                    startX += @ViewBag.Map.LenOfPixel;
                </text>
            }
            <text>
                startX = 10;
                startY += @ViewBag.Map.LenOfPixel;
            </text>
        }
    };
</script>
<body>
<canvas id="canvas3" width="@newWidth" height="@newHeight"></canvas>
    @Html.ActionLink("Prev", "DrawHeatMap", "Map")
    @Html.ActionLink("Restart", "Index", "Map")
    @Html.ActionLink("Next", "DrawBiomeMap", "Map")
<button onclick="saveCanvasAsImageFile(2,`Moisture Map`)">
Download
</button>
</body>

src/src/Views/Map/Index.cshtml
@{
    Layout = "_Layout1";
    ViewData["Title"] = "Home Page";
    string[] sizes = {"200x200", "300x300", "400x400", "500x500", "600x600","700x700","800x800"};
    const int length = 5;
}

<h1>@ViewData["Title"]</h1>
<br />

@using (Html.BeginForm("Index", "Map"))
{
    <label>Chose the size of map:</label>
    <select name="sizeId">
        @for (int i = 0; i < sizes.Length; ++i)
        {
            <option value="@i">@sizes[i]</option>
        }
    </select>
  
    <select name="lenOfPix">
            
        @for (int i = 1; i <= length; ++i)
        {
            <option value="@(i)">@(i)px</option>
        }

    </select>
   
    <p>  
        <span>Create Rivers: </span>
        @Html.CheckBox("hasRiver", false)
        <span>Create Castles: </span>
        @Html.CheckBox("hasCastles", false)
        <span>Create Particles: </span>
        @Html.CheckBox("hasParticles", false)
    </p>
    
    <input class="form-submit-button" type="submit" value="Submit"/>
}

src/src/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - src</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/CourseWork.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - src - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/src/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"]</title>
    <script src="js/site.js"></script>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Course_work.styles.css" asp-append-version="true"/>
</head>
<body>
@RenderBody()

</body>
</html>

src/src/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"]</title>
    <script>
    const canvasId = ["canvas1","canvas2","canvas3","canvas4"]
    function drawRect(canvasId, x, y, red, green, blue, lenOfPix, num) {
        let ctx = canvasId[num];
        if (!ctx) return;
        ctx.fillStyle = `rgb(${red},${green},${blue})`;
        ctx.fillRect(x, y, lenOfPix, lenOfPix);
    }
      
    function getImage(canvas){
        let imageData = canvas.toDataURL();
        let image = new Image();
        image.src = imageData;
        return image;
    }
    
    function saveImage(image,name) {
        let link = document.createElement("a");
    
        link.setAttribute("href", image.src);
        link.setAttribute("download", name);
        link.click();
    }
    
    function saveCanvasAsImageFile(num,name){
        let image = getImage(document.getElementById(canvasId[num]));
        saveImage(image,name);
    }
    </script> 
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Course_work.styles.css" asp-append-version="true"/>
</head>

<body>
<h1>@ViewData["Title"]</h1>
<br />
@RenderBody()
</body>
</html>